"""empty message

Revision ID: 2815428fc8b8
Revises: f3c4e7f7bdc5
Create Date: 2023-10-29 15:46:28.714134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2815428fc8b8'
down_revision = 'f3c4e7f7bdc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.alter_column('fee_total',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fees_student_id_fkey', type_='foreignkey')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Fees', sa.Integer(), nullable=False))
        batch_op.alter_column('fee_paid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'fees', ['Fees'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('fee_paid',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('Fees')

    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fees_student_id_fkey', 'students', ['student_id'], ['id'])
        batch_op.alter_column('fee_total',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
