"""empty message

Revision ID: 290fa6ec34ad
Revises: 5a37ed0140ba
Create Date: 2023-11-14 13:29:05.425724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290fa6ec34ad'
down_revision = '5a37ed0140ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
