"""empty message

Revision ID: 37bc68a3f1a5
Revises: e278ad33fb2b
Create Date: 2023-11-14 16:04:31.967043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bc68a3f1a5'
down_revision = 'e278ad33fb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=50), server_default=sa.text("'true'::character varying"), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
