"""empty message

Revision ID: 3e0a3909ce9e
Revises: c071f44c520c
Create Date: 2023-10-25 10:24:29.952776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0a3909ce9e'
down_revision = 'c071f44c520c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_paid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('balance', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('balance')
        batch_op.drop_column('fee_paid')

    op.drop_table('fees')
    # ### end Alembic commands ###
