"""empty message

Revision ID: 524a73543a50
Revises: d97656c77589
Create Date: 2023-11-30 11:56:50.202844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524a73543a50'
down_revision = 'd97656c77589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment')
    # ### end Alembic commands ###
