"""empty message

Revision ID: 5f345b78c023
Revises: d7a27312a494
Create Date: 2023-10-23 20:32:31.954485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f345b78c023'
down_revision = 'd7a27312a494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emai', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_students_emai'), ['emai'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_emai'))
        batch_op.drop_column('emai')

    # ### end Alembic commands ###
