"""empty message

Revision ID: 61256d52f289
Revises: 837e9c308c30
Create Date: 2023-10-24 20:07:48.472685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61256d52f289'
down_revision = '837e9c308c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fee_paid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('balance', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('balance')
        batch_op.drop_column('fee_paid')
        batch_op.drop_column('fee_total')

    # ### end Alembic commands ###
