"""empty message

Revision ID: 719e9444c47a
Revises: c3fd5816eb31
Create Date: 2023-11-14 17:21:33.016557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719e9444c47a'
down_revision = 'c3fd5816eb31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
