"""empty message

Revision ID: 7c45fdd54b1a
Revises: 3dd3da7bc45b
Create Date: 2023-12-02 09:40:19.394401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c45fdd54b1a'
down_revision = '3dd3da7bc45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_constraint('module_parent_module_id_fkey', type_='foreignkey')
        batch_op.drop_column('parent_module_id')
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('parent_module_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('module_parent_module_id_fkey', 'module', ['parent_module_id'], ['id'])

    # ### end Alembic commands ###
