"""empty message

Revision ID: 90b4203315a2
Revises: 444c44789d70
Create Date: 2023-11-28 12:16:38.193987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b4203315a2'
down_revision = '444c44789d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_module_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'module', ['parent_module_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_module_id')

    # ### end Alembic commands ###
