"""empty message

Revision ID: 921e5bc8127f
Revises: 01b665d27506
Create Date: 2023-11-14 17:04:15.308569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921e5bc8127f'
down_revision = '01b665d27506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
