"""empty message

Revision ID: 9bd377b5c7c9
Revises: 61256d52f289
Create Date: 2023-10-25 09:51:08.022603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd377b5c7c9'
down_revision = '61256d52f289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('balance')
        batch_op.drop_column('fee_paid')
        batch_op.drop_column('fee_total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_total', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fee_paid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('balance', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
