"""empty message

Revision ID: a161e6053675
Revises: a627d2aa01ab
Create Date: 2023-10-25 21:54:38.808432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a161e6053675'
down_revision = 'a627d2aa01ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.drop_constraint('fees_student_id_fkey', type_='foreignkey')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_total', sa.Float(), nullable=False))
        batch_op.create_foreign_key(None, 'fees', ['fee_total'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fee_total')

    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fees_student_id_fkey', 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###
