"""empty message

Revision ID: a92ba8ae50df
Revises: c94624675895
Create Date: 2023-10-27 13:19:14.250544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92ba8ae50df'
down_revision = 'c94624675895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('students_fee_total_fkey', type_='foreignkey')
        batch_op.drop_column('fee_total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_total', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('students_fee_total_fkey', 'fees', ['fee_total'], ['id'])

    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
