"""empty message

Revision ID: c071f44c520c
Revises: 9bd377b5c7c9
Create Date: 2023-10-25 10:11:08.108820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c071f44c520c'
down_revision = '9bd377b5c7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_total', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_paid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('balance', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('balance')
        batch_op.drop_column('fee_paid')

    op.drop_table('fees')
    # ### end Alembic commands ###
