"""empty message

Revision ID: c3fd5816eb31
Revises: 5ed2e09e5652
Create Date: 2023-11-14 17:14:28.548875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = 'c3fd5816eb31'
down_revision = '5ed2e09e5652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=50), nullable=False))
        op.execute(text("UPDATE users SET image_file = 'default.jpg'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_file')


    # ### end Alembic commands ###
