"""empty message

Revision ID: d5a11cf1bea3
Revises: b08aad8818a1
Create Date: 2023-10-29 21:10:52.764013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a11cf1bea3'
down_revision = 'b08aad8818a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('second_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('fee_paid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_first_name'), ['first_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_second_name'), ['second_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_second_name'))
        batch_op.drop_index(batch_op.f('ix_students_first_name'))
        batch_op.drop_index(batch_op.f('ix_students_email'))

    op.drop_table('students')
    op.drop_table('fees')
    # ### end Alembic commands ###
