"""empty message

Revision ID: ddd9a1893339
Revises: c794e394be18
Create Date: 2023-12-01 08:51:47.380605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd9a1893339'
down_revision = 'c794e394be18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user'], ['id'])

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_index('ix_enrollment_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.create_index('ix_enrollment_username', ['username'], unique=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user')

    # ### end Alembic commands ###
